import { requestById, SLOT_MINUTES, WINDOW_END } from "../data/requests";
import { categoryOf, categoryProfile } from "../engine/conflicts";
import { conflictKey } from "../engine/resolutions";
import { isFeasible, validate, type ValidationContext } from "../engine/validate";
import { priorityWeight, type AlternativeSlot, type Plan, type ViolationRuleId } from "../types/railplan";

/** Minimum separation between two alternatives, so the list is not three near-identical slots. */
const DIVERSITY_MINUTES = 30;
const MAX_ALTERNATIVES = 3;

/**
 * Alternative slots for one request, generated by re-solving rather than
 * guessing.
 *
 * The rest of the plan is held still and every candidate start is put to the
 * validator. Only slots that come back clean are offered, and each carries the
 * movement it costs. A slot that cannot be made to work is not shown at all;
 * the binding rule is reported instead.
 */
export function findAlternatives(
  plan: Plan,
  requestId: string,
  context: ValidationContext = {},
): { alternatives: AlternativeSlot[]; bindingRuleId: ViolationRuleId | null } {
  const request = requestById[requestId];
  if (!request) return { alternatives: [], bindingRuleId: null };

  const windowEnd = context.windowEnd ?? WINDOW_END;
  const current = plan.placements.find((placement) => placement.requestId === requestId);
  const others = plan.placements.filter((placement) => placement.requestId !== requestId);
  const latest =
    Math.min(request.latestEnd, windowEnd - request.clearanceMinutes) - request.durationMinutes;

  // What this request is currently in trouble for. Naming the categories an
  // alternative clears is the difference between "this slot validates" and an
  // answer a planner can act on.
  const baselineAll = validate(plan, context).filter((violation) => violation.severity === "critical");
  const baselineKeys = new Set(baselineAll.map(conflictKey));
  const baselineCategories = [
    ...new Set(
      baselineAll
        .filter((violation) => violation.requestIds.includes(requestId))
        .map((violation) => categoryProfile[categoryOf(violation.ruleId)].label),
    ),
  ];

  const feasibleStarts: number[] = [];
  const blockedBy = new Map<ViolationRuleId, number>();

  for (let start = request.earliestStart; start <= latest; start += SLOT_MINUTES) {
    if (current && start === current.startMinute) continue;

    const trial: Plan = {
      placements: [
        ...others,
        {
          requestId,
          startMinute: start,
          endMinute: start + request.durationMinutes,
          teamId: request.teamId,
          locked: false,
        },
      ],
      deferred: plan.deferred.filter((entry) => entry.requestId !== requestId),
    };

    const trialAll = validate(trial, context).filter((violation) => violation.severity === "critical");
    const violations = trialAll.filter((violation) => violation.requestIds.includes(requestId));

    if (violations.length) {
      violations.forEach((violation) =>
        blockedBy.set(violation.ruleId, (blockedBy.get(violation.ruleId) ?? 0) + 1),
      );
      continue;
    }
    // Clean for this request is not enough: a slot that pushes the problem onto
    // somebody else is not an alternative, it is a trade, and is not offered.
    if (trialAll.some((violation) => !baselineKeys.has(conflictKey(violation)))) continue;

    feasibleStarts.push(start);
  }

  // Prefer slots closest to what the requester actually asked for, then apply a
  // diversity filter so the planner sees genuinely different options.
  const ranked = feasibleStarts.sort(
    (a, b) => Math.abs(a - request.preferredStart) - Math.abs(b - request.preferredStart) || a - b,
  );

  const chosen: number[] = [];
  for (const start of ranked) {
    if (chosen.length >= MAX_ALTERNATIVES) break;
    if (chosen.some((existing) => Math.abs(existing - start) < DIVERSITY_MINUTES)) continue;
    chosen.push(start);
  }

  const currentMovement = current ? Math.abs(current.startMinute - request.preferredStart) : null;
  const weight = priorityWeight[request.priority];

  const alternatives: AlternativeSlot[] = chosen
    .sort((a, b) => a - b)
    .map((start, index) => {
      const movement = Math.abs(start - request.preferredStart);
      const delta = currentMovement === null ? movement : movement - currentMovement;
      return {
        id: `${requestId}-alt-${index + 1}`,
        requestId,
        startMinute: start,
        endMinute: start + request.durationMinutes,
        feasible: true,
        displacedRequestIds: [],
        movementMinutesDelta: delta,
        // Nothing else moved, so the placed set — and therefore weighted
        // completion — is unchanged. Reported as 0 rather than omitted so the
        // card cannot be read as "unknown".
        weightedCompletionDelta: currentMovement === null ? Math.round((weight / 1) * 0) : 0,
        bindingRuleId: null,
        summary: buildSummary(delta, currentMovement),
        whyItWorks: baselineCategories.length
          ? `Clears the ${joinWords(baselineCategories.map((label) => label.toLowerCase()))}. Every other rule re-checked at this start.`
          : "Sector, crew, equipment and sequencing all check clear at this start.",
        impact: buildImpact(start, current?.startMinute ?? null, movement),
      };
    });

  const binding =
    [...blockedBy.entries()].sort((a, b) => b[1] - a[1])[0]?.[0] ?? null;

  return { alternatives, bindingRuleId: binding };
}

function joinWords(items: string[]): string {
  if (items.length <= 1) return items[0] ?? "";
  return `${items.slice(0, -1).join(", ")} and ${items[items.length - 1]}`;
}

/**
 * The cost of taking an option. "No other request moves" is a checked claim:
 * every candidate offered was validated with the rest of the plan held still.
 */
function buildImpact(start: number, currentStart: number | null, fromRequested: number): string {
  const parts: string[] = [];
  if (currentStart !== null && start !== currentStart) {
    const shift = Math.abs(start - currentStart);
    parts.push(`${shift} min ${start > currentStart ? "later" : "earlier"} than now`);
  }
  parts.push(
    fromRequested === 0
      ? "at the requested time"
      : `${fromRequested} min from the requested time`,
  );
  parts.push("no other request moves");
  return parts.join(" · ");
}

function buildSummary(delta: number, currentMovement: number | null): string {
  if (currentMovement === null) {
    return delta === 0
      ? "Places the work at its requested time."
      : `Places the work ${delta} minutes from its requested time.`;
  }
  if (delta === 0) return "Same distance from the requested time as the current placement.";
  if (delta < 0) return `Moves ${Math.abs(delta)} minutes closer to the requested time.`;
  return `Moves ${delta} minutes further from the requested time.`;
}

/**
 * Apply a planner's chosen alternative and re-validate.
 *
 * The result is authoritative: if the override breaks something, the caller
 * gets the violations back rather than a plan that merely looks different.
 */
export function applyAlternative(
  plan: Plan,
  requestId: string,
  startMinute: number,
  context: ValidationContext = {},
): { plan: Plan; violations: ReturnType<typeof validate>; feasible: boolean } {
  const request = requestById[requestId];
  if (!request) return { plan, violations: [], feasible: true };

  const next: Plan = {
    placements: [
      ...plan.placements.filter((placement) => placement.requestId !== requestId),
      {
        requestId,
        startMinute,
        endMinute: startMinute + request.durationMinutes,
        teamId: request.teamId,
        locked: plan.placements.find((p) => p.requestId === requestId)?.locked ?? false,
      },
    ].sort((a, b) => a.startMinute - b.startMinute || a.requestId.localeCompare(b.requestId)),
    deferred: plan.deferred.filter((entry) => entry.requestId !== requestId),
  };

  const violations = validate(next, context);
  return { plan: next, violations, feasible: isFeasible(violations) };
}
